const hobbies = [
  "To Read",
  "To Paint",
  "DO Cooking",
  "GO Hiking",
  "Do Gardening",
  "Practice Photography",
  "Play a Musical Instrument",
  "Dance",
  "Sing",
  "Write",
  "Go Biking",
  "Go Fishing",
  "Do Yoga",
  "Play Gaming",
  "Birdwatching",
  "Swimming",
  "Camping",
  "Traveling",
  "Skiing",
  "Sculpting",
  "Woodworking",
  "Sewing",
  "Meditation",
  "Collecting Stamps",
  "Rock Climbing",
  "Volunteering",
  "Pottery",
  "Calligraphy",
  "Study Astrology",
  "Go Geocaching",
  "Play Chess",
  "Model Building",
  "Try Skydiving",
  "Go Surfing",
  "Cycling",
  "Auto Racing",
  "Try Bungee Jumping",
  "Kayaking",
  "Ice Skating",
  "Go Scuba Diving",
  "Make Candles",
  "Fossil Hunting",
  "Practice Photography",
  "Play Paintball",
  "Study Astronomy",
  "Metal Detecting",
  "Motorcycling",
  "Go Whale Watching",
  "Stargazing",
  "Whittle",
  "Practice Tai Chi",
  "Play Soccer",
  "Practice Yoga",
  "Play Chess",
  "Practice Martial Arts",
  "Play Tennis",
  "Practice Meditation",
  "Play Golf",
  "Practice Mindfulness",
  "Play Basketball",
  "Practice Painting",
  "Play Video Games",
  "Practice Coding",
  "Play the Piano",
  "Practice Photography",
];
export default hobbies;
