const cancionesTaylorSwift = [
    "Love Story",
    "You Belong with Me",
    "Blank Space",
    "Shake It Off",
    "Bad Blood",
    "Wildest Dreams",
    "Delicate",
    "Lover",
    "Cardigan",
    "Willow",
    "22",
    "Style",
    "I Knew You Were Trouble",
    "All Too Well",
    "Red",
    "Me!",
    "Our Song",
    "White Horse",
    "Teardrops on My Guitar",
    "Fearless",
    "Mine",
    "Speak Now",
    "Mean",
    "Back to December",
    "Dear John",
    "Enchanted",
    "Ours",
    "State of Grace",
    "The Last Time",
    "Clean",
    "Welcome to New York",
    "Out of the Woods",
    "New Romantics",
    "End Game",
    "Getaway Car",
    "I Forgot That You Existed",
    "Cruel Summer",
    "The 1",
    "August",
    "Betty",
    "Exile",
    "The Archer",
    "Death by a Thousand Cuts",
    "Invisible String",
    "Peace",
    "Gold Rush",
    "Cowboy Like Me",
    "you're on your own kid",
    "Marjorie",
    "Closure",
    "Evermore",
    "Willow",
    "No Body, No Crime",
    "Happiness",
    "Dorothea",
    "Coney Island",
    "Ivy",
    "Cowboy Like Me",
    "Long Live Taylor´s version",
    "Marjorie",
    "Closure",
    "Evermore",
    "Willow",
    "Champagne Problems",
    "No Body, No Crime",
    "Happiness",
    "Dorothea",
    "Coney Island",
    "Ivy",
    "Epiphany",
    "Mad Woman",
    "Betty's Garden",
    "Dark Blue Tennessee",
    "Ronan",
    "Sparks Fly",
    "This Love",
    "You Are in Love",
    "All You Had to Do Was Stay",
    "Breathe",
    "Jump Then Fall",
    "The Other Side of the Door",
    "Stay Stay Stay",
    "Holy Ground",
    "Treacherous",
    "Come Back... Be Here",
    "Welcome to New York",
    "Out of the Woods",
    "New Romantics",
  ];
  export default cancionesTaylorSwift;